# Handwritten Digit Classifier

## Importing the libraries

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

## Importing the dataset

In [3]:
from tensorflow.keras.datasets import mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [4]:
X_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [5]:
X_test

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [6]:
X_train.shape

(60000, 28, 28)

In [7]:
X_test.shape

(10000, 28, 28)

***So we have 60000 samples in the training data and 10000 samples in the test data***
The shape of the images is 28x28 and the pixel values ranges from 0-255

## Data Preprocessing

### Flattening the array into 1D

In [8]:
X_train = X_train.reshape(-1, 28*28)
X_test = X_test.reshape(-1, 28*28)

In [10]:
X_train.shape

(60000, 784)

In [11]:
X_test.shape

(10000, 784)

In [12]:
y_train.shape

(60000,)

In [13]:
y_test.shape

(10000,)

### Applying Normalization

In [14]:
X_train = X_train / 255.0
X_test = X_test / 255.0

**We can also use MinMaxScaler but here using this method is preferred.**

In [18]:
print(X_train)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


### One Hot Encoding using tensorflow

In [20]:
from tensorflow.keras.utils import to_categorical
y_train = to_categorical(y_train, num_classes = 10)
y_test = to_categorical(y_test, num_classes = 10)

In [22]:
y_train.shape

(60000, 10)

In [23]:
y_test.shape

(10000, 10)

## Buliding the ANN Model

In [38]:
ann = tf.keras.models.Sequential()

### Input Layer

In [45]:
ann.add(tf.keras.layers.Dense(units = 784, activation = "relu"))

### Hidden Layer 1

In [46]:
ann.add(tf.keras.layers.Dense(units = 64, activation = "relu"))

### Hidden Layer 2

In [47]:
ann.add(tf.keras.layers.Dense(units = 32, activation = "relu"))

### Output Layer

In [48]:
ann.add(tf.keras.layers.Dense(units = 10, activation = "softmax"))

## Compiling the ANN

In [49]:
ann.compile(optimizer= "adam", loss = "categorical_crossentropy", metrics = ["accuracy"])

## Fitting the model

In [50]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 10)

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 29s 14ms/step - accuracy: 0.9695 - loss: 0.2524
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 41s 14ms/step - accuracy: 0.9896 - loss: 0.0581
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 26s 14ms/step - accuracy: 0.9905 - loss: 0.0493
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 26s 14ms/step - accuracy: 0.9928 - loss: 0.0353
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 42s 14ms/step - accuracy: 0.9924 - loss: 0.0347
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 40s 14ms/step - accuracy: 0.9943 - loss: 0.0261
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 41s 14ms/step - accuracy: 0.9934 - loss: 0.0304
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 40s 13ms/step - accuracy: 0.9924 - loss: 0.0333
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 26s 14ms/step - accuracy: 0.9939 - loss: 0.0244
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 27s 14ms/step - accuracy: 0.9944 - loss: 0.0259


In [54]:
y_pred = ann.predict(X_test)
y_pred = np.argmax(y_pred, axis = 1)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step


In [57]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_test_labels = np.argmax(y_test, axis=1)
cm = confusion_matrix(y_test_labels, y_pred)
print(cm)
train_accuracy = accuracy_score(y_test_labels, y_pred)

[[ 973    1    0    0    0    1    4    1    0    0]
 [   0 1122    0    1    0    2    5    0    5    0]
 [   5    0 1010    4    0    1    1    5    6    0]
 [   1    0    1  983    0   18    0    3    1    3]
 [   0    0    2    0  956    0   10    3    2    9]
 [   2    0    0    2    1  882    3    0    1    1]
 [   4    2    0    0    1    4  945    0    2    0]
 [   1    3    5    4    0    0    0 1004    4    7]
 [   9    1    1    1    1    5    3    5  944    4]
 [   2    2    1    4   10    2    0    6    1  981]]


In [59]:
val_loss, val_accuracy = ann.evaluate(X_test, y_test)
print(f"Validation Accuracy: {val_accuracy * 100:.2f}%")
print(f"Training Accuracy: {train_accuracy * 100:.2f}%")

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9746 - loss: 0.1263
Validation Accuracy: 98.00%
Training Accuracy: 98.00%


In [60]:
ann.save("mnist_ann_model.h5")